# Étape de construction avec Node.js
FROM node:18.17-alpine as builder

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers de package et installer les dépendances
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copier le reste des fichiers de l'application
COPY . .

# Compiler l'application TypeScript
RUN npm run build

# Étape de production, copie des fichiers nécessaires et nettoyage
FROM node:18.17-alpine
WORKDIR /app

# Définir NODE_ENV sur production
# ENV NODE_ENV=production PORT=1605 MONGO_URL=http://localhost:15

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules

# Exposer le port sur lequel l'application s'exécute
EXPOSE 1605

# Définir la commande pour démarrer l'application
CMD ["node", "dist/main"]
